export var ColourID;
(function (ColourID) {
    ColourID[ColourID["Red"] = 0] = "Red";
    ColourID[ColourID["Blue"] = 1] = "Blue";
    ColourID[ColourID["DarkGreen"] = 2] = "DarkGreen";
    ColourID[ColourID["Pink"] = 3] = "Pink";
    ColourID[ColourID["Orange"] = 4] = "Orange";
    ColourID[ColourID["Yellow"] = 5] = "Yellow";
    ColourID[ColourID["Black"] = 6] = "Black";
    ColourID[ColourID["White"] = 7] = "White";
    ColourID[ColourID["Purple"] = 8] = "Purple";
    ColourID[ColourID["Brown"] = 9] = "Brown";
    ColourID[ColourID["Cyan"] = 10] = "Cyan";
    ColourID[ColourID["Lime"] = 11] = "Lime";
})(ColourID || (ColourID = {}));
export const ColorID = ColourID;
export var DisconnectID;
(function (DisconnectID) {
    DisconnectID[DisconnectID["None"] = 0] = "None";
    DisconnectID[DisconnectID["GameFull"] = 1] = "GameFull";
    DisconnectID[DisconnectID["GameStarted"] = 2] = "GameStarted";
    DisconnectID[DisconnectID["GameNotFound"] = 3] = "GameNotFound";
    DisconnectID[DisconnectID["OldCustom"] = 4] = "OldCustom";
    DisconnectID[DisconnectID["OutdatedClient"] = 5] = "OutdatedClient";
    DisconnectID[DisconnectID["Banned"] = 6] = "Banned";
    DisconnectID[DisconnectID["Kicked"] = 7] = "Kicked";
    DisconnectID[DisconnectID["Custom"] = 8] = "Custom";
    DisconnectID[DisconnectID["InvalidUsername"] = 9] = "InvalidUsername";
    DisconnectID[DisconnectID["Hacking"] = 10] = "Hacking";
    DisconnectID[DisconnectID["Force"] = 16] = "Force";
    DisconnectID[DisconnectID["BadConnection"] = 17] = "BadConnection";
    DisconnectID[DisconnectID["GameNotFound2"] = 18] = "GameNotFound2";
    DisconnectID[DisconnectID["ServerClosed"] = 19] = "ServerClosed";
    DisconnectID[DisconnectID["ServerOverloaded"] = 20] = "ServerOverloaded";
})(DisconnectID || (DisconnectID = {}));
export var DistanceID;
(function (DistanceID) {
    DistanceID[DistanceID["Short"] = 0] = "Short";
    DistanceID[DistanceID["Medium"] = 1] = "Medium";
    DistanceID[DistanceID["Long"] = 2] = "Long";
})(DistanceID || (DistanceID = {}));
export var TaskBarUpdate;
(function (TaskBarUpdate) {
    TaskBarUpdate[TaskBarUpdate["Always"] = 0] = "Always";
    TaskBarUpdate[TaskBarUpdate["InMeetings"] = 1] = "InMeetings";
    TaskBarUpdate[TaskBarUpdate["Never"] = 2] = "Never";
})(TaskBarUpdate || (TaskBarUpdate = {}));
export var MessageID;
(function (MessageID) {
    MessageID[MessageID["Data"] = 1] = "Data";
    MessageID[MessageID["RPC"] = 2] = "RPC";
    MessageID[MessageID["Spawn"] = 4] = "Spawn";
    MessageID[MessageID["Despawn"] = 5] = "Despawn";
    MessageID[MessageID["SceneChange"] = 6] = "SceneChange";
    MessageID[MessageID["Ready"] = 7] = "Ready";
    MessageID[MessageID["ChangeSettings"] = 8] = "ChangeSettings";
})(MessageID || (MessageID = {}));
export var HatID;
(function (HatID) {
    HatID[HatID["NoHat"] = 0] = "NoHat";
    HatID[HatID["Astronaut"] = 1] = "Astronaut";
    HatID[HatID["BaseballCap"] = 2] = "BaseballCap";
    HatID[HatID["BrainSlug"] = 3] = "BrainSlug";
    HatID[HatID["BushHat"] = 4] = "BushHat";
    HatID[HatID["CaptainsHat"] = 5] = "CaptainsHat";
    HatID[HatID["DoubleTopHat"] = 6] = "DoubleTopHat";
    HatID[HatID["Flowerpot"] = 7] = "Flowerpot";
    HatID[HatID["Goggles"] = 8] = "Goggles";
    HatID[HatID["HardHat"] = 9] = "HardHat";
    HatID[HatID["Military"] = 10] = "Military";
    HatID[HatID["PaperHat"] = 11] = "PaperHat";
    HatID[HatID["PartyHat"] = 12] = "PartyHat";
    HatID[HatID["Police"] = 13] = "Police";
    HatID[HatID["Stethescope"] = 14] = "Stethescope";
    HatID[HatID["TopHat"] = 15] = "TopHat";
    HatID[HatID["TowelWizard"] = 16] = "TowelWizard";
    HatID[HatID["Ushanka"] = 17] = "Ushanka";
    HatID[HatID["Viking"] = 18] = "Viking";
    HatID[HatID["WallCap"] = 19] = "WallCap";
    HatID[HatID["Snowman"] = 20] = "Snowman";
    HatID[HatID["Reindeer"] = 21] = "Reindeer";
    HatID[HatID["Lights"] = 22] = "Lights";
    HatID[HatID["Santa"] = 23] = "Santa";
    HatID[HatID["Tree"] = 24] = "Tree";
    HatID[HatID["Present"] = 25] = "Present";
    HatID[HatID["Candycanes"] = 26] = "Candycanes";
    HatID[HatID["ElfHat"] = 27] = "ElfHat";
    HatID[HatID["NewYears2018"] = 28] = "NewYears2018";
    HatID[HatID["WhiteHat"] = 29] = "WhiteHat";
    HatID[HatID["Crown"] = 30] = "Crown";
    HatID[HatID["Eyebrows"] = 31] = "Eyebrows";
    HatID[HatID["HaloHat"] = 32] = "HaloHat";
    HatID[HatID["HeroCap"] = 33] = "HeroCap";
    HatID[HatID["PipCap"] = 34] = "PipCap";
    HatID[HatID["PlungerHat"] = 35] = "PlungerHat";
    HatID[HatID["ScubaHat"] = 36] = "ScubaHat";
    HatID[HatID["StickminHat"] = 37] = "StickminHat";
    HatID[HatID["StrawHat"] = 38] = "StrawHat";
    HatID[HatID["TenGallonHat"] = 39] = "TenGallonHat";
    HatID[HatID["ThirdEyeHat"] = 40] = "ThirdEyeHat";
    HatID[HatID["ToiletPaperHat"] = 41] = "ToiletPaperHat";
    HatID[HatID["Toppat"] = 42] = "Toppat";
    HatID[HatID["Fedora"] = 43] = "Fedora";
    HatID[HatID["Goggles_2"] = 44] = "Goggles_2";
    HatID[HatID["Headphones"] = 45] = "Headphones";
    HatID[HatID["MaskHat"] = 46] = "MaskHat";
    HatID[HatID["PaperMask"] = 47] = "PaperMask";
    HatID[HatID["Security"] = 48] = "Security";
    HatID[HatID["StrapHat"] = 49] = "StrapHat";
    HatID[HatID["Banana"] = 50] = "Banana";
    HatID[HatID["Beanie"] = 51] = "Beanie";
    HatID[HatID["Bear"] = 52] = "Bear";
    HatID[HatID["Cheese"] = 53] = "Cheese";
    HatID[HatID["Cherry"] = 54] = "Cherry";
    HatID[HatID["Egg"] = 55] = "Egg";
    HatID[HatID["Fedora_2"] = 56] = "Fedora_2";
    HatID[HatID["Flamingo"] = 57] = "Flamingo";
    HatID[HatID["FlowerPin"] = 58] = "FlowerPin";
    HatID[HatID["Helmet"] = 59] = "Helmet";
    HatID[HatID["Plant"] = 60] = "Plant";
    HatID[HatID["BatEyes"] = 61] = "BatEyes";
    HatID[HatID["BatWings"] = 62] = "BatWings";
    HatID[HatID["Horns"] = 63] = "Horns";
    HatID[HatID["Mohawk"] = 64] = "Mohawk";
    HatID[HatID["Pumpkin"] = 65] = "Pumpkin";
    HatID[HatID["ScaryBag"] = 66] = "ScaryBag";
    HatID[HatID["Witch"] = 67] = "Witch";
    HatID[HatID["Wolf"] = 68] = "Wolf";
    HatID[HatID["Pirate"] = 69] = "Pirate";
    HatID[HatID["Plague"] = 70] = "Plague";
    HatID[HatID["Machete"] = 71] = "Machete";
    HatID[HatID["Fred"] = 72] = "Fred";
    HatID[HatID["MinerCap"] = 73] = "MinerCap";
    HatID[HatID["WinterHat"] = 74] = "WinterHat";
    HatID[HatID["Archae"] = 75] = "Archae";
    HatID[HatID["Antenna"] = 76] = "Antenna";
    HatID[HatID["Balloon"] = 77] = "Balloon";
    HatID[HatID["BirdNest"] = 78] = "BirdNest";
    HatID[HatID["BlackBelt"] = 79] = "BlackBelt";
    HatID[HatID["Caution"] = 80] = "Caution";
    HatID[HatID["Chef"] = 81] = "Chef";
    HatID[HatID["CopHat"] = 82] = "CopHat";
    HatID[HatID["DoRag"] = 83] = "DoRag";
    HatID[HatID["DumSticker"] = 84] = "DumSticker";
    HatID[HatID["Fez"] = 85] = "Fez";
    HatID[HatID["GeneralHat"] = 86] = "GeneralHat";
    HatID[HatID["GreyThing"] = 87] = "GreyThing";
    HatID[HatID["HunterCap"] = 88] = "HunterCap";
    HatID[HatID["JungleHat"] = 89] = "JungleHat";
    HatID[HatID["MiniCrewmate"] = 90] = "MiniCrewmate";
    HatID[HatID["NinjaMask"] = 91] = "NinjaMask";
    HatID[HatID["RamHorns"] = 92] = "RamHorns";
    HatID[HatID["Snowman_2"] = 93] = "Snowman_2";
})(HatID || (HatID = {}));
export var LanguageID;
(function (LanguageID) {
    LanguageID[LanguageID["Any"] = 0] = "Any";
    LanguageID[LanguageID["Other"] = 1] = "Other";
    LanguageID[LanguageID["English"] = 256] = "English";
    LanguageID[LanguageID["Spanish"] = 2] = "Spanish";
    LanguageID[LanguageID["Korean"] = 4] = "Korean";
    LanguageID[LanguageID["Russian"] = 8] = "Russian";
    LanguageID[LanguageID["Portuguese"] = 16] = "Portuguese";
    LanguageID[LanguageID["Arabic"] = 32] = "Arabic";
    LanguageID[LanguageID["Filipino"] = 64] = "Filipino";
    LanguageID[LanguageID["Polish"] = 128] = "Polish";
})(LanguageID || (LanguageID = {}));
export var SystemType;
(function (SystemType) {
    SystemType[SystemType["Hallway"] = 0] = "Hallway";
    SystemType[SystemType["Storage"] = 1] = "Storage";
    SystemType[SystemType["Cafeteria"] = 2] = "Cafeteria";
    SystemType[SystemType["Reactor"] = 3] = "Reactor";
    SystemType[SystemType["UpperEngine"] = 4] = "UpperEngine";
    SystemType[SystemType["Navigations"] = 5] = "Navigations";
    SystemType[SystemType["Administrator"] = 6] = "Administrator";
    SystemType[SystemType["Electrical"] = 7] = "Electrical";
    SystemType[SystemType["O2"] = 8] = "O2";
    SystemType[SystemType["Shields"] = 9] = "Shields";
    SystemType[SystemType["MedBay"] = 10] = "MedBay";
    SystemType[SystemType["Security"] = 11] = "Security";
    SystemType[SystemType["Weapons"] = 12] = "Weapons";
    SystemType[SystemType["LowerEngine"] = 13] = "LowerEngine";
    SystemType[SystemType["Communications"] = 14] = "Communications";
    SystemType[SystemType["ShipTasks"] = 15] = "ShipTasks";
    SystemType[SystemType["Doors"] = 16] = "Doors";
    SystemType[SystemType["Sabotage"] = 17] = "Sabotage";
    SystemType[SystemType["Decontamination"] = 18] = "Decontamination";
    SystemType[SystemType["Launchpad"] = 19] = "Launchpad";
    SystemType[SystemType["LockerRoom"] = 20] = "LockerRoom";
    SystemType[SystemType["Laboratory"] = 21] = "Laboratory";
    SystemType[SystemType["Balcony"] = 22] = "Balcony";
    SystemType[SystemType["Office"] = 23] = "Office";
    SystemType[SystemType["Greenhouse"] = 24] = "Greenhouse";
})(SystemType || (SystemType = {}));
export var MapID;
(function (MapID) {
    MapID[MapID["TheSkeld"] = 0] = "TheSkeld";
    MapID[MapID["MiraHQ"] = 1] = "MiraHQ";
    MapID[MapID["Polus"] = 2] = "Polus";
})(MapID || (MapID = {}));
export var PacketID;
(function (PacketID) {
    PacketID[PacketID["Unreliable"] = 0] = "Unreliable";
    PacketID[PacketID["Reliable"] = 1] = "Reliable";
    PacketID[PacketID["Hello"] = 8] = "Hello";
    PacketID[PacketID["Disconnect"] = 9] = "Disconnect";
    PacketID[PacketID["Acknowledge"] = 10] = "Acknowledge";
    PacketID[PacketID["Ping"] = 12] = "Ping";
})(PacketID || (PacketID = {}));
export var PayloadID;
(function (PayloadID) {
    PayloadID[PayloadID["HostGame"] = 0] = "HostGame";
    PayloadID[PayloadID["JoinGame"] = 1] = "JoinGame";
    PayloadID[PayloadID["StartGame"] = 2] = "StartGame";
    PayloadID[PayloadID["RemoveGame"] = 3] = "RemoveGame";
    PayloadID[PayloadID["RemovePlayer"] = 4] = "RemovePlayer";
    PayloadID[PayloadID["GameData"] = 5] = "GameData";
    PayloadID[PayloadID["GameDataTo"] = 6] = "GameDataTo";
    PayloadID[PayloadID["JoinedGame"] = 7] = "JoinedGame";
    PayloadID[PayloadID["EndGame"] = 8] = "EndGame";
    PayloadID[PayloadID["AlterGame"] = 10] = "AlterGame";
    PayloadID[PayloadID["Redirect"] = 13] = "Redirect";
    PayloadID[PayloadID["MasterServerList"] = 14] = "MasterServerList";
    PayloadID[PayloadID["GameList"] = 16] = "GameList";
})(PayloadID || (PayloadID = {}));
export var RPCID;
(function (RPCID) {
    RPCID[RPCID["PlayAnimation"] = 0] = "PlayAnimation";
    RPCID[RPCID["CompleteTask"] = 1] = "CompleteTask";
    RPCID[RPCID["SyncSettings"] = 2] = "SyncSettings";
    RPCID[RPCID["SetInfected"] = 3] = "SetInfected";
    RPCID[RPCID["Exiled"] = 4] = "Exiled";
    RPCID[RPCID["CheckName"] = 5] = "CheckName";
    RPCID[RPCID["SetName"] = 6] = "SetName";
    RPCID[RPCID["CheckColour"] = 7] = "CheckColour";
    RPCID[RPCID["SetColour"] = 8] = "SetColour";
    RPCID[RPCID["SetHat"] = 9] = "SetHat";
    RPCID[RPCID["SetSkin"] = 10] = "SetSkin";
    RPCID[RPCID["ReportDeadBody"] = 11] = "ReportDeadBody";
    RPCID[RPCID["MurderPlayer"] = 12] = "MurderPlayer";
    RPCID[RPCID["SendChat"] = 13] = "SendChat";
    RPCID[RPCID["StartMeeting"] = 14] = "StartMeeting";
    RPCID[RPCID["SetScanner"] = 15] = "SetScanner";
    RPCID[RPCID["SendChatNote"] = 16] = "SendChatNote";
    RPCID[RPCID["SetPet"] = 17] = "SetPet";
    RPCID[RPCID["SetStartCounter"] = 18] = "SetStartCounter";
    RPCID[RPCID["EnterVent"] = 19] = "EnterVent";
    RPCID[RPCID["ExitVent"] = 20] = "ExitVent";
    RPCID[RPCID["SnapTo"] = 21] = "SnapTo";
    RPCID[RPCID["Close"] = 22] = "Close";
    RPCID[RPCID["VotingComplete"] = 23] = "VotingComplete";
    RPCID[RPCID["CastVote"] = 24] = "CastVote";
    RPCID[RPCID["ClearVote"] = 25] = "ClearVote";
    RPCID[RPCID["AddVote"] = 26] = "AddVote";
    RPCID[RPCID["CloseDoorsOfType"] = 27] = "CloseDoorsOfType";
    RPCID[RPCID["RepairSystem"] = 28] = "RepairSystem";
    RPCID[RPCID["SetTasks"] = 29] = "SetTasks";
    RPCID[RPCID["UpdateGameData"] = 30] = "UpdateGameData";
})(RPCID || (RPCID = {}));
export var DataID;
(function (DataID) {
    DataID[DataID["Movement"] = 6] = "Movement";
})(DataID || (DataID = {}));
export var PetID;
(function (PetID) {
    PetID[PetID["None"] = 0] = "None";
    PetID[PetID["Alien"] = 1] = "Alien";
    PetID[PetID["Crewmate"] = 2] = "Crewmate";
    PetID[PetID["Doggy"] = 3] = "Doggy";
    PetID[PetID["Stickmin"] = 4] = "Stickmin";
    PetID[PetID["Hamster"] = 5] = "Hamster";
    PetID[PetID["Robot"] = 6] = "Robot";
    PetID[PetID["UFO"] = 7] = "UFO";
    PetID[PetID["Ellie"] = 8] = "Ellie";
    PetID[PetID["Squig"] = 9] = "Squig";
    PetID[PetID["Bedcrab"] = 10] = "Bedcrab";
})(PetID || (PetID = {}));
export var SkinID;
(function (SkinID) {
    SkinID[SkinID["None"] = 0] = "None";
    SkinID[SkinID["Astro"] = 1] = "Astro";
    SkinID[SkinID["Capt"] = 2] = "Capt";
    SkinID[SkinID["Mech"] = 3] = "Mech";
    SkinID[SkinID["Military"] = 4] = "Military";
    SkinID[SkinID["Police"] = 5] = "Police";
    SkinID[SkinID["Science"] = 6] = "Science";
    SkinID[SkinID["SuitB"] = 7] = "SuitB";
    SkinID[SkinID["SuitW"] = 8] = "SuitW";
    SkinID[SkinID["Wall"] = 9] = "Wall";
    SkinID[SkinID["Hazmat"] = 10] = "Hazmat";
    SkinID[SkinID["Security"] = 11] = "Security";
    SkinID[SkinID["Tarmac"] = 12] = "Tarmac";
    SkinID[SkinID["Miner"] = 13] = "Miner";
    SkinID[SkinID["Winter"] = 14] = "Winter";
    SkinID[SkinID["Archae"] = 15] = "Archae";
})(SkinID || (SkinID = {}));
export var SpawnID;
(function (SpawnID) {
    SpawnID[SpawnID["ShipStatus"] = 0] = "ShipStatus";
    SpawnID[SpawnID["MeetingHub"] = 1] = "MeetingHub";
    SpawnID[SpawnID["LobbyBehaviour"] = 2] = "LobbyBehaviour";
    SpawnID[SpawnID["GameData"] = 3] = "GameData";
    SpawnID[SpawnID["Player"] = 4] = "Player";
    SpawnID[SpawnID["HeadQuarters"] = 5] = "HeadQuarters";
    SpawnID[SpawnID["PlanetMap"] = 6] = "PlanetMap";
    SpawnID[SpawnID["AprilShipStatus"] = 7] = "AprilShipStatus";
})(SpawnID || (SpawnID = {}));
export var TaskID;
(function (TaskID) {
    TaskID[TaskID["SubmitScan"] = 0] = "SubmitScan";
    TaskID[TaskID["PrimeShields"] = 1] = "PrimeShields";
    TaskID[TaskID["FuelEngines"] = 2] = "FuelEngines";
    TaskID[TaskID["CharCourse"] = 3] = "CharCourse";
    TaskID[TaskID["StartReactor"] = 4] = "StartReactor";
    TaskID[TaskID["SwipeCard"] = 5] = "SwipeCard";
    TaskID[TaskID["ClearAsteroids"] = 6] = "ClearAsteroids";
    TaskID[TaskID["UploadData"] = 7] = "UploadData";
    TaskID[TaskID["InspectSample"] = 8] = "InspectSample";
    TaskID[TaskID["EmptyChute"] = 9] = "EmptyChute";
    TaskID[TaskID["EmptyGarbage"] = 10] = "EmptyGarbage";
    TaskID[TaskID["AlignEngineOutput"] = 11] = "AlignEngineOutput";
    TaskID[TaskID["FixWiring"] = 12] = "FixWiring";
    TaskID[TaskID["CalibrateDistributor"] = 13] = "CalibrateDistributor";
    TaskID[TaskID["DivertPower"] = 14] = "DivertPower";
    TaskID[TaskID["UnlockManifolds"] = 15] = "UnlockManifolds";
    TaskID[TaskID["ResetReactor"] = 16] = "ResetReactor";
    TaskID[TaskID["FixLights"] = 17] = "FixLights";
    TaskID[TaskID["CleanO2Filter"] = 18] = "CleanO2Filter";
    TaskID[TaskID["FixCommucations"] = 19] = "FixCommucations";
    TaskID[TaskID["RestoreOxygen"] = 20] = "RestoreOxygen";
    TaskID[TaskID["StablizeSteering"] = 21] = "StablizeSteering";
    TaskID[TaskID["AssembleArtifact"] = 22] = "AssembleArtifact";
    TaskID[TaskID["SortSamples"] = 23] = "SortSamples";
    TaskID[TaskID["MeasureWeather"] = 24] = "MeasureWeather";
    TaskID[TaskID["EnterIdCode"] = 25] = "EnterIdCode";
})(TaskID || (TaskID = {}));
export var GameEndReason;
(function (GameEndReason) {
    GameEndReason[GameEndReason["HumansByVote"] = 0] = "HumansByVote";
    GameEndReason[GameEndReason["HumansByTask"] = 1] = "HumansByTask";
    GameEndReason[GameEndReason["ImposterByVote"] = 2] = "ImposterByVote";
    GameEndReason[GameEndReason["ImposterByKill"] = 3] = "ImposterByKill";
    GameEndReason[GameEndReason["ImposterBySabotage"] = 4] = "ImposterBySabotage";
    GameEndReason[GameEndReason["ImposterDisconnect"] = 5] = "ImposterDisconnect";
    GameEndReason[GameEndReason["HumansDisconnect"] = 6] = "HumansDisconnect";
})(GameEndReason || (GameEndReason = {}));
export var AlterGameTag;
(function (AlterGameTag) {
    AlterGameTag[AlterGameTag["ChangePrivacy"] = 1] = "ChangePrivacy";
})(AlterGameTag || (AlterGameTag = {}));
